### ISSUE TITLE
ch données : exercices supplémentaires

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#15]
J'ai mis sur le drive (alm/exercices-supplémentaires) des idées d'énoncés. On peut les simplifier en donnant un pas à pas ou au contraire ne donner que le diagramme de classes commenté.

**Comment by mcodutti** [comment]
J'ai intégré les exercices "Lièvre et Tortue" et "Casino" dans le chapitre sur la représentation des données. Pour les autres, j'ai pas trop le courage d'autant qu'il y en a déjà bien assez ainsi.
Merci.
