### ISSUE TITLE
Chapitre Liste - Parler de l'implémentation

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/DEV2-ALG-Syllabus-Algo#17]
Il  n'y a que 4h consacrées à ce chapitre.
Une option serait de ne plus parler de l'implémentation; on verrait les méthodes sans parler de leur implémentation : plus de tableau dynamique et d'agrandissement de tableau.
Votre opinion ?

**Comment by cuv** [comment]
Je remarque qu'il n'y a plus d'exercice utilisant cet implémentation. Pour ma part je laisserais cette théorie même si on ne la donne pas par manque de temps. Elle peut aider à la compréhension de certains.

**Comment by mcodutti** [comment]
OK c'est laissé.
