### ISSUE TITLE
ch oo petite image 

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#19]
Si on a le temps...

Sur http://www.universocomputacao.com/object-oriented-thinking/ il y a une chouette image d'une classe chien et d'un objet chien.

et ici un bon schéma privé-publique. http://upload.wikimedia.org/wikipedia/commons/thumb/8/82/CPT-OOP-interfaces.svg/450px-CPT-OOP-interfaces.svg.png

**Comment by mcodutti** [comment]
Je ne suis pas hyper-convaincu par ses images là.
J'y réfléchis...

**Comment by mcodutti** [comment]
Ce n'est plus d'actualité, vu la réduction du chapitre.
