### ISSUE TITLE
TDM pdf

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV2-ALG-Syllabus-Algo#27]
Dans les signets du pdf (la TDM qu'on voit à gauche dans adobe reader) tous les chapitres sont à l'intérieur du chapitre OO. Il faudrait les séparer.

**Comment by mcodutti** [comment]
Je ne comprends pas pourquoi !

**Comment by mcodutti** [comment]
Réglé dans cette version, même si je ne sais pas pourquoi.
