### ISSUE TITLE
Tableau p. 23

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV2-ALG-Syllabus-Algo#28]
Le premier tableau p. 23 (sec 2.4.1) (avec la ligne "l" en bleu) a une barre verticale en trop à la fin. Pour les tableaux suivants il y a des traits qui manquent pour les cases bleues (pas grave)

**Comment by mcodutti** [comment]
Je ne vois pas ça sur mon PDF.
Peut-être que les lignes sont très fines et que ça dépend de la résolution de son écran.
À voir ce que ça donne à l'impression.

**Comment by mcodutti** [comment]
Apparemment, ça n'était plus présent à l'impression.
