### ISSUE TITLE
Ch1 justifier règle constructeur

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#3]
Justifier pourquoi un constructeur ne peut appeler un autre constructeur de la même classe

**Comment by mcodutti** [comment]
Je relis le syllabus et je ne vois que de rares cas où ce pourrait être utile. Pour le moment, le syllabus n'en fait même plus mention, ce qui me parait bien afin qu'il y ait le moins de règles possibles.
