### ISSUE TITLE
tableaux exercice 9

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV2-ALG-Syllabus-Algo#31]
Exercice 9d: la question est mal définie dans le cas où n n'est pas un multiple de 3 +1. J'ai chaque année des difficultés avec cela car plusieurs généralisations différentes, pour ce motif, sont alors possibles. Je propose de dire que pour celui-là n est toujours un multiple de 3 + 1. 
Exercice 9f: je trouve cet exercice trop difficile, je propose de l'enlever.

**Comment by mcodutti** [comment]
J'ai ajouté ces 2 remarques
```	Notes
	\begin{liste}
	\item 
		Le zèbre doit toujours présenter des lignes
		obliques et parallèles, quelle que soit la taille.
	\item
		La spirale est un véritable défi
		et vous est donné comme exercice facultatif.
		Ne le faites pas si vous êtes en retard.
	\end{liste}
```
