### ISSUE TITLE
Liste et généricité

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV2-ALG-Syllabus-Algo#32]
Je n'aime pas trop l'emploi de la généricité tel quel au début du chapitre sur les listes car ils n'ont pas vu ce concept avant, et il me semble qu'il est très dur d'apprendre deux nouveaux concepts en même temps: je pense que si on veut faire de la généricité alors il faut l'introduire en tant que telle, avant les listes, dans un chapitre dédié. Sinon, je pense qu'il faut se limiter dans nos exemples à des listes d'entiers, quitte à introduire la généricité en toute fin de ce chapitre dans une section à part nommée "listes génériques" (ou ne pas faire de généricité du tout) mais je n'aime pas l'idée que dès la première page de ce chapitre, deux nouveaux concept (tout à fait différents, à savoir la généricité et les listes) sont enseignés "en même temps", ce qui à mon avis n'est pas très pédagogique, je pense que chaque chapitre doit enseigner un message (surtout en début de chapitre).

**Comment by mcodutti** [comment]
Si on fait un chapitre dédié, il comprendra 5 lignes !
On ne fait pas vraiment de la généricité ici et on se fout de toutes les complications techniques que ça implique. On veut juste dire que ça marche pour tout type d'élément.

On peut commencer avec un type concret et puis passer à T juste avant les exercices mais alors il faudra prendre autre chose que entier sinon il y aura confusion dans les entêtes de méthode entre les entiers qui indiquent un élément et ceux qui indiquent une position.

**Comment by mcodutti** [comment]
J'ai fait quelques changements, à voir si ça suffit.

**Comment by cathleruste** [comment]
J'interviens un peu tard et je n'ai pas encore lu les changements de Marco mais, pour info, en alg-dev1, dans "8.6 Parcours d’un tableau à une dimension",on y lit :
tab : tableau [1 à n] de T // où T est un type quelconque
C'est une notation simple et ça n'a choqué aucun (de mes ?) étudiant(s).
