### ISSUE TITLE
Liste: exemples

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV2-ALG-Syllabus-Algo#33]
Je pense que avant de donner l'exemple de la recheche du minimum, il faut donner des exemples du concept de liste du point de vue logique, avec des dessins de listes (avec des boules connectées par des flèches ou bien la notation "<1,5,9>" ) et des dessins de ce qui se passe quand on ajoute/supprime des éléments (voir comment la liste évolue, graphiquement), donc donner des petits appels de diverses méthodes d'insertion/suppressions et montrer comment la liste évolue alors. Car sinon ils n'ont pas encore au début assez de compréhension des différentes opérations de base sur les listes pour vraiment bien sentir le concept et pour bien comprendre des codes comme la recherche du minimum, et aussi pour bien comprendre l'utilité des listes (et leurs différences) par rapport aux tableaux

**Comment by mcodutti** [comment]
Bonne idée.
Mais je ne mettrais pas de boules avec des flèches car ce ne sont pas des listes chainées.
Je mettrais simplement une liste comme une liste de courses
```1) premier élément
2) deuxième élément
3) troisième élement
```
