### ISSUE TITLE
OO - ex 2 - anniversaire

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/DEV2-ALG-Syllabus-Algo#39]
Comme beaucoup ont du mal à se remettre aux algo, on peut suggérer une étape intermédiaire en résolvant d'abord une version non OO de l'exercice.
"Écrire un module qui lit une série de nombres et affiche ceux qui sont pairs. -1 est la valeur sentinelle. À la fin, le module affiche le nombre de valeurs paires"

**Comment by fservais-heb** [comment]
pas sûr que cela les aide à faire le saut vers l'OO.
Il n'y a que 2 séances sur OO, si en plus on fait autre chose, cela devient vraiment léger, non?

**Comment by cuv** [comment]
Je propose de leur demander d'écrire (ré-écrire) un des exemples utilisés
dans la théorie. Moi je donne la théorie sur l'exemple produit, je l'écrit
au tableau. Je leur demande d'ré-écrire cette classe sans la copier ;-)
avant le premier exercice. Donc ils n'auront pas le temps de faire les deux
exercices en classe.

**Comment by mcodutti** [comment]
Vu la réduction du chapitre, cette issue est devenue obsolète.
