### ISSUE TITLE
Liste et paramètres entrant-sortant

### ISSUE THREAD

**Issue by fservais-heb** [HEB-ESI/DEV2-ALG-Syllabus-Algo#41]
Une méthode reçoit en paramètre une liste.
Cette méthode utilise la méthode supprimer.
Doit-on déclarer le paramètre en tant que paramètre sortant?

**Comment by mcodutti** [comment]
Pour moi, oui.
En algo, les flèches indiquent l'intention. Ici, on modifie la liste -> IN/OUT.
C'est dans la même idée qu'un tableau dont on modifierait une valeur.
