### ISSUE TITLE
ch 1 visualisation : type caractère non vu

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#42]
En 1.2.2 on a bien changé l'exemple pour ne plus avoir de type caractère, non vu en DEV1 cette année.
En 1.2.3 l'exemple de l'année passée (type caractère) est resté.

**Comment by mcodutti** [comment]
Je passe à des entiers mais il ne faudra pas avoir peur d'introduire "caractère" comme un raccourci pour "chaine de taille 1" sans voir toutes les opérations qui vont avec; ce n'est pas compliqué.
