### ISSUE TITLE
Ch1 méthode égale

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#5]
1.8 on dit : "On supposera par la suite qu’une telle méthode existe par défaut pour toutes les
nouvelles classes" et dans l'exemple on écrit le code de la méthode égal. Peut être mettre en commentaire qu'elle peut ne pas être écrite. Et si la méthode égale n'est pas triviale (autre qu'une comparaison attribut par attribut avec l'opérateur = ), elle existe tout de même par défaut?

**Comment by mcodutti** [comment]
Cf. #14 
J'ai supprimé égal et considéré, poyur simplifier, que = compare l'état
