### ISSUE TITLE
Ch 4 plus progressif?

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#51]
Lors de la réunion de juin dernier il était demandé de rendre ce chapitre plus progressif.
(-- mélanger les types, 
-- combinaison liste et tableau, 
-- énoncés plus corsés cfr mail du 8 juin)

J'ai relu les derniers examen de DEV2 et ont plusieurs questions avec une description de données. 

Je trouve donc que ce dernier chapitre ne correspond pas aux derniers examens.

Que fait-on?

**Comment by cuv** [comment]
Je propose : 
- mettre les énoncés dans un ordre de difficulté croissante Le premier énoncé est trop simple, le supprimer. Par exemple: commencer avec les tableaux 1D : Q2, Q5 puis tableaux 1D de structure Q6, puis  tableaux 2D Q9 avec structures Q4, puis liste et tableau Q7, enfin les autres sans description de la représentation des données.
- pour les premiers énoncés, donner une aide pour trouver la représentation des données  et  de progressivement diminuer cet aide
- de décomposer les premiers énoncés en sous questions et de progressivement supprimer les sous questions.
- Je pense qu'il y a trop d'énoncé.

**Comment by mcodutti** [comment]
Je vais voir ce que je peux faire.
Je garderais bien le 1 avec une solution complète, histoire de justifier les choix faits et de montrer la démarche.

**Comment by cuv** [comment]
Pour le premier je donnerais deux exemples de solution, une avec une représentation de données demandant un algo compliqué et une facilitant l'algo. Le but est de montrer l'importance de ce choix de représentation de données. (A mon avis avec la Q1 ceci sera difficile )

**Comment by mcodutti** [comment]
J'avais en tête de faire une solution non oo et puis de la transformer en
oo.
Le 15 janv. 2016 09:39, "cuv" <notifications@github.com> a écrit :

> Pour le premier je donnerais deux exemples de solution, une avec une
> représentation de données demandant un algo compliqué et une facilitant
> l'algo. Le but est de montrer l'importance de ce choix de représentation de
> données. (A mon avis avec la Q1 ceci sera difficile )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/51#issuecomment-171902567>
> .
>

-- 
Haute École de Bruxelles

**Comment by cuv** [comment]
Le passage à l'oo ne montre pas tjs l'importance du choix d'une bonne représentation des données. C'est un autre objectif pédagogique. Ce passage devrait être dans la chapitre oo. Ici je me concentrerais sur les données dans un env. oo ou non oo.

**Comment by mcodutti** [comment]
J'ai enlevé l'exercice 1 et je l'ai déplacé dans le chapitre OO comme une mise en pratique avec une solution détaillée, progressive et commentée sur 5 pages !
J'hésite même à aller plus loin en introduisant une classe Jeu avec des méthodes comme jouerCoup() et estJeuFini() et parler un peu de MVC. 
Trop compliqué ? 
Une bonne introduction pour mieux comprendre l'énoncé du projet en DEV2-JAVL ?
