### ISSUE TITLE
ch oo Lièvre et tortue

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#53]
p 23 s/sinontortue.avancer()/sinon  tortue.avancer()/

J'aime bien cet exemple progressif non oo puis oo pour un jeu. J'aime que l'on montre le processus de résolution.  

Merci :D

**Comment by mcodutti** [comment]
Alors je l'ai continué avec une version "MVC".

**Comment by cathleruste** [comment]
C'est vraiment une excellente idée de montrer les 3 approches de façon progressive !
Merci !
