### ISSUE TITLE
Ch 4 proposition d'idée pour le premier exercice 

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#54]
Jeu de poursuite: l'exercice pourrait commencer comme ceci:

Voici 3 propositions de représentation de données. On vous demande pour chaque proposition de vérifier, sans écrire l'algorithme, si elle permet la programmation du jeu. Après ces vérifications vous choisirez une des représentations pour écrire l'algorithme demandé. 

proposition 1: circuit: un tableau de 50 chaines de caractères numérotés de 1 à 50. Les chaines de caractères représenterons la position des joueurs. (au départ, "A" en 1 et "B" en 26, " " dans les autres positions) ;    joueurCourant: entier donnant la position du joueur courant.

proposition 2: circuit: un tableau de 50 éléments Joueur (Structure Joueur nom: chaine; nbTour: entier)  numérotés de 1 à 50. Joueur reprendra le nom du joueur à cette position ("A","B" ou "" si la case est vide); nbTour donne le nombre de tour qu' a fait le joueur qui est à cette position. (0 si la case est vide)

proposition 3: tableau de 2 éléments Joueur (Structure Joueur position: entier; nbTour: entier) où position donne la position du joueur sur le circuit (entier entre 1 et 50) et nbTour donne le nombre de tour qu' a fait le joueur.

**Comment by cuv** [comment]
J'ai oublier de mettre joueurCourant dans les propositions 2 et 3

**Comment by mcodutti** [comment]
Pas mal. Mais comme certains trouvent cet exercice compliqué (au niveau algorithmique, c'est difficile pour un étudiant de voir comment se rendre compte qu'on rattrape l'autre), ne pourrait-on pas suivre la même démarche d'abord sur un jeu plus simple :
- n joueurs sur un plateau de 64 cases; chaque joueur avance en lançant un dé; le premier arrivé a gagné.
- seule contrainte : si on arrive sur une case déjà occupée, on rejoue.

Propositions : 
1) Un tableau de 64 entiers (i si le joueur i s'y trouve ou 0 si libre)
2) Un tableau de 1 à n entiers (la position du joueur i est stockée en i)
3) On combine la 1 et la 2

Pour casser mon idée, je dirais que la proposition 1) est à rejeter pour 2 raisons : difficile de savoir où se trouve le joueur i mais aussi impossible de les placer tous au départ. Ce serait bien de trouver un exercice où une seule des deux causes interviendrait.

Continuons à y réfléchir; je m'y met lundi.
Merci.

**Comment by mcodutti** [comment]
Voilà une proposition que je n'ai pas encore pris le temps de relire dans le détail, d'où de probables coquilles encore.
Est-ce que ça va dans la bonne direction ?

**Comment by cathleruste** [comment]
Je relis et je poste au fur et à mesure de la lecture. 

4.3-1-2 : tu voulais vraiment écrire "Un tableau de 1 à n entiers" au lieu de "Un tableau de 4 entiers" ? C'est déjà pour répondre au 4.3-2 ?

**Comment by cathleruste** [comment]
4.3-4 : 
- "Le constructeur reçoit la configuration du circuit (pour savoir si les cases contiennent vrai ou faux)" : on ne dit pas ce que représente le vrai/faux. Surtout que par la suite, on parle de tableau de chaines
- jouer() (...) donne (...) le nombre de tours effectués. : quand considérer qu'un tour est effectué ? Quand "A est repassé par la case 1 ou B par la case 26" ou "quand A ou B a dépassé la case 50" ?
- Les différentes propositions : 
-- proposition 4 : peut-être préciser les méthodes ?
-- proposition 5 : reformuler sous une forme proche du 4

**Comment by mcodutti** [comment]
Il faut remplacer le n par 4. Au départ, c'était directement n et puis j'ai
fait une première version à 4 joueurs pour graduer la difficulté mais j'ai
oublié de changer le n.

Le 26 janvier 2016 à 13:23, cathleruste <notifications@github.com> a écrit :

> Je relis et je poste au fur et à mesure de la lecture.
>
> 4.3-1-2 : tu voulais vraiment écrire "Un tableau de 1 à n entiers" au lieu
> de "Un tableau de 4 entiers" ? C'est déjà pour répondre au 4.3-2 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/54#issuecomment-174979279>
> .
>

-- 
Haute École de Bruxelles

**Comment by mcodutti** [comment]
4.3-4: Toujours des coquilles liées aux modifications de dernière minute
pour graduer la difficulté
1) Il faudrait supprimer ce constructeur et le réintroduire dans l'exercice
suivant.
2) Je ne sais pas; ça vient de la proposition de CUV
3) Je ne te suis pas; fais le changement qui te convient.

Le 26 janvier 2016 à 14:25, Codutti, Marco <mcodutti@heb.be> a écrit :

> Il faut remplacer le n par 4. Au départ, c'était directement n et puis
> j'ai fait une première version à 4 joueurs pour graduer la difficulté mais
> j'ai oublié de changer le n.
>
> Le 26 janvier 2016 à 13:23, cathleruste <notifications@github.com> a
> écrit :
>
>> Je relis et je poste au fur et à mesure de la lecture.
>>
>> 4.3-1-2 : tu voulais vraiment écrire "Un tableau de 1 à n entiers" au
>> lieu de "Un tableau de 4 entiers" ? C'est déjà pour répondre au 4.3-2 ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/54#issuecomment-174979279>
>> .
>>
>
>

-- 
Haute École de Bruxelles

**Comment by cathleruste** [comment]
Je n'ai pas encore écrit les résolutions d'exercices mais j'aime bien la gradation de difficulté.
Merci pour le travail !

**Comment by mcodutti** [comment]
Ce serait bien qu'on ait un planning pour savoir combien de temps on a pour
chaque chapitre et notamment ici, pour le dernier, afin d'estimer le nombre
d'exercices qu'on pourra faire avec eux.


Le 26 janvier 2016 à 14:39, cathleruste <notifications@github.com> a écrit :

> Je n'ai pas encore écrit les résolutions d'exercices mais j'aime bien la
> gradation de difficulté.
> Merci pour le travail !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/54#issuecomment-175017331>
> .
>

-- 
Haute École de Bruxelles

**Comment by cathleruste** [comment]
Je me disais la même chose. Y a-t-il, quelque part, un planning de l'année dernière sur lequel on peut se baser ?

**Comment by cathleruste** [comment]
(clairement pas sur poEsi ^^)

**Comment by mcodutti** [comment]
Laurent nous l'avait envoyé par mail; je te l'ai transféré.


2016-01-26 14:44 GMT+01:00 cathleruste <notifications@github.com>:

> (clairement pas sur poEsi ^^)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/54#issuecomment-175019559>
> .
>

-- 
Haute École de Bruxelles

**Comment by cuv** [comment]
Hello, 

Pour moi nbTour (4-3-4) compte le nombre de tour fait par un joueur, on l'incrémente quand le joueur est ou dépasse sa position de départ.

Pour le constructeur, je ne voie pas pourquoi le circuit doit être initialisé de vrai/faux. (J'ai aussi cela dans ma solution, a mon avis cela date d'une ancienne version un peu différente...)

Pour la dernière proposition (4-3-4) " Cette proposition est fort proche..." ne devrait pas être un nouveau point dans la liste des propositions.

**Comment by cathleruste** [comment]
Tu t'attends à quoi comme méthodes ?
Les getteurs, avancer, aDépassé, ... ? Le texte est trop vague à mon gout...

**Comment by mcodutti** [comment]
Voilà, j'ai essayé de clarifier.
Pour graduer la difficulté, exit la proposition "classe" qui devient un exercice placé avant "Casino".
Ainsi, avant de devoir imaginer leurs classes et méthodes (comme c'est le cas à partir de l'exercice Casino), ils auront un exercice de transformation d'un version pas tout-à-fait 00 en une version plus OO.

**Comment by cathleruste** [comment]
Déplacer la demande sous forme de classe avant "Congés" me convient ainsi que la formulation des exercices 4 et 5. 
Merci pour le boulot !

**Comment by cuv** [comment]
Super ces énoncés progressifs.
Mais on parle de classe dès le début, je ne comprends pas quand se passe la traduction non oo en oo.
Ces exercices 1 à 5, vous comptez les faire en 1 séance de 2h ou plus? Nous avons que 3 * 2h pour ce chapitre...

**Comment by mcodutti** [comment]
Pour moi, la classe c'est juste pour mettre tout ensemble sans trop
insister mais c'est vrai que c'est pas très cohérent. On peut enlever toute
référence OO aux exercices 1 à 5. On aurait alors :
- ex. 1 à 5 : réflexion sur les données dans un cadre non OO (course64 +
poursuite)
- ex. 6 et 7 : exercice très dirigé avec des structures et une classe
(millionaire + hôtel)
- ex. 8 : exercice très dirigé purement OO (ensemble)
- ex. 9 et 10 : on demande à passer en OO les exercices "course 64" +  "jeu
de la poursuite" (que j'ajouterais)
- ex. 11 à 15 : exercices libres avec OO (casino...)

Ca vous convient mieux ?

Le 27 janvier 2016 à 12:21, cuv <notifications@github.com> a écrit :

> Super ces énoncés progressifs.
> Mais on parle de classe dès le début, je ne comprends pas quand se passe
> la traduction non oo en oo.
> Ces exercices 1 à 5, vous comptez les faire en 1 séance de 2h ou plus?
> Nous avons que 3 * 2h pour ce chapitre...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/54#issuecomment-175568278>
> .
>

-- 
Haute École de Bruxelles

**Comment by cuv** [comment]
Oui, j'aime mieux. Mais arrivera-t-on à l'exercice 10 en 3 * 2h? 
Les années précédantes je prennais une séance par énoncé!

**Comment by mcodutti** [comment]
Voilà, à relire attentivement.
Clairement, c'est beaucoup pour le temps dont on dispose.
Peut-être peut-on gagner 1h ou 2 avec les listes.
Pour le reste, il faudra qu'ils travaillent bien à la maison.
Pas l'idéal, mais j'ai pas mieux :(

**Comment by cathleruste** [comment]
On peut décider ceux que l'on ferait tous en classe et ceux que les étudiants pourraient développer lors des 6 heures de remédiation en préparation à l'examen ?

**Comment by mcodutti** [comment]
Bonne idée.

**Comment by cathleruste** [comment]
Si je relis tes modifs ce soir, il est encore temps ?
On ajouterait un tag pour s'assurer que tout le monde fasse les mêmes exercices ?

**Comment by mcodutti** [comment]
Oui, je publie demain.
Je ne mettrais pas les tags, qu'on ait le temps de mûrir la question.
On n'est pas très nombreux, on arrivera bien à se mettre d'accord ;)

**Comment by cathleruste** [comment]
Parfait pour moi, merci pour le boulot !
