### ISSUE TITLE
Ch4 solution oo ou non?

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#55]
Pour ce chapitre va-t-on imposer une solution oo pour tous les exercices, ou pour certains ou on laisse le choix? Va-t-on jusqu'à demander une solution MVC?

**Comment by mcodutti** [comment]
Je dirais non pour MVC; en tout cas pas systématiquement; c'est probablement encore difficile pour des 1ère. Pour l'OO; j'y serais déjà plus favorable.
