### ISSUE TITLE
primitive erreur

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/DEV2-ALG-Syllabus-Algo#56]
Il me semblait avoir vu passer la remarque mais la primitive "erreur" n'a pas été introduit en alm1.
Je n'ai aucun problème à l'utiliser en alm2 car ils connaissent l'équivalent Java (+ explication donnée en pied de page).
Si quelqu'un a un problème avec ça, qu'il en parle maintenant ou ...

**Comment by eythanlevy** [comment]
Pas de problème pour moi!
Le 26 janv. 2016 10:55, "cathleruste" <notifications@github.com> a écrit :

> Il me semblait avoir vu passer la remarque mais la primitive "erreur" n'a
> pas été introduit en alm1.
> Je n'ai aucun problème à l'utiliser en alm2 car ils connaissent
> l'équivalent Java.
> Si quelqu'un a un problème avec ça, qu'il en parle maintenant ou ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/56>.
>

-- 
Haute École de Bruxelles

**Comment by ahallal** [comment]
Le noter au moins une fois dans le syllabus DEV2 serait bien. Pour la
syntaxe. A moins que c'est déjà fait ;)

Le 26 janvier 2016 à 12:39, eythanlevy <notifications@github.com> a écrit :

> Pas de problème pour moi!
> Le 26 janv. 2016 10:55, "cathleruste" <notifications@github.com> a écrit :
>
> > Il me semblait avoir vu passer la remarque mais la primitive "erreur" n'a
> > pas été introduit en alm1.
> > Je n'ai aucun problème à l'utiliser en alm2 car ils connaissent
> > l'équivalent Java.
> > Si quelqu'un a un problème avec ça, qu'il en parle maintenant ou ...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/56>.
> >
>
> --
> Haute École de Bruxelles
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/56#issuecomment-174965513>
> .
>

-- 
Haute École de Bruxelles

**Comment by mcodutti** [comment]
Dans ALG1, "erreur" apparaît dans l'annexe C, "Le LDA" mais n'est jamais utilisé.
Dans ALG2, "erreur" n’apparaît que dans les implémentations des méthodes de listes.
Idéalement, ce serait plus propre de parler de précondition sans écrire explicitement le test mais on n'est trop près de l'échéance pour introduire les notions de pré et post conditions.
Pour moi, on peut simplement ajouter un commentaire en début de méthode du genre : "i doit être compris entre 0 et tailleLogique -1" et supprimer le test.

**Comment by mcodutti** [comment]
J'ai ajouté une note sur la primitive "erreur" en annexe mais j'ai aussi enlevé toutes les références dans Liste (précondition mise en commentaire à la place)
