### ISSUE TITLE
Aide-mémoire ?

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/DEV2-ALG-Syllabus-Algo#59]
Reprend-t-on l'aide mémoire de ALG1 en y ajoutant la classe Liste ?
Ca ne devrait pas me prendre trop de temps pour le faire.

**Comment by cathleruste** [comment]
Ok pour moi. Je le fais (pas avant 22h aujourd'hui) ou tu t'en charges ?

**Comment by mcodutti** [comment]
Fait !
