### ISSUE TITLE
Ch1 exercices

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV2-ALG-Syllabus-Algo#6]
Exercice1. Je demanderais de créer et manipuler des objets Produits.(module A) Puis de modifier la classe Produit pour qu'un produit soit en rupture de stock si sa quantité en stock est inférieur ou égal à un seuil x(imposé tjs le même).  Puis je demanderais ce qu'il faut modifier dans le module A. Et si le seuil est propre à chaque produit, que modifier dans la classe, dans le module A?

Exercice 2. Je ne mettrais pas de date ici. Je mettrais un exercice spécifique pour la classe Date mais plus loin. Faire remarquer le problème de la validation.
Exercice3 : après l'exercice sur Date
Exercice 4: Nous les avons assommés avec cet énoncé en algo1;-) Ne multiplions pas les difficultés (oo + géométrie ;-)).  Par exemple mettre à la place un énoncé pour faire un bulletin (etudiant, étude, cours, cotes...).

**Comment by mcodutti** [comment]
J'ai du réduire fortement le nombre d'exercices pour coller au nb d'heures allouées (4h).
J'ai gardé l'exercice sur les anniversaires.
