### ISSUE TITLE
Type générique

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/DEV2-ALG-Syllabus-Algo#62]
Ça pose un problème si je remplace les "de T" par "<T>" pour être cohérent avec dev4 ?

**Comment by mcodutti** [comment]
Et tu fais comment dans la signature des méthodes ?

Le 27 janvier 2016 à 17:31, cathleruste <notifications@github.com> a écrit :

> Ça pose un problème si je remplace les "de T" par "" pour être cohérent
> avec dev4 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/62>.
>

-- 
Haute École de Bruxelles

**Comment by cathleruste** [comment]
il faut lire par "\<T\>" (oublié d'échapper les \< dans le message précédent)

**Comment by mcodutti** [comment]
Je trouve ma notation plus fluide mais la tienne étant pareille à Java,
pourquoi pas. Ce sera peut-être plus simple pour les étudiants. Tu as mon
accord.
Le 27 janv. 2016 17:43, "cathleruste" <notifications@github.com> a écrit :

> il faut lire par "<T>" (oublié d'échapper les < dans le message précédent)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV2-ALG-Syllabus-Algo/issues/62#issuecomment-175737370>
> .
>

-- 
Haute École de Bruxelles

**Comment by cathleruste** [comment]
J'ai du mal à être cohérente moi-même dans la notation. Finalement, gardons le "de T" ^^
