### ISSUE TITLE
énumération

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/DEV2-ALG-Syllabus-Algo#70]
La notion d'énumération n'est plus présentée, ni en dev1, ni en dev2. Pourtant, on en parle dans le ch.4, ex.15 du Mastermind.
On pourrait au moins rajouter la notion en annexe, non ?

**Comment by cuv** [comment]
​Oui avec une redirection dans l'énoncé du mastermind.
​


2016-07-30 14:03 GMT+02:00 cathleruste <notifications@github.com>:

**Comment by mcodutti** [comment]
J'ai ajouté une annexe "Compléments" avec le texte repris du syllabus d'il y a 3 ans.
