### ISSUE TITLE
Lien vers description "le lièvre et la tortue" inexistant

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/DEV2-ALG-Syllabus-Algo#72]
Section 2.4 page 20 (OO, Mise en pratique : le lièvre et la tortue) le document 
http://mathemathieu.free.fr/2b/doc/pb_algo/problemes_et_algorithmique.pdf n'est plus accessible. impossible dans ces conditions d'avoir la description du jeu et de bien le comprendre.

**Comment by mcodutti** [comment]
La page en question ne contenait pas plus que ce que j'ai mis juste après dans "description du jeu".
Je vais juste supprimer le lien et ajouter un petit schéma (perfectible).

**Comment by cathleruste** [comment]
J'aime vraiment bien le petit schéma mais j'ai l'impression que la tortue doit parcourir 6 km avant de gagner :s

**Comment by mcodutti** [comment]
C'est vrai.
Celle-ci a été trouvée sur le web.
Si quelqu'un a envie d'en faire une moins ambigüe...


2017-01-29 23:38 GMT+01:00 cathleruste <notifications@github.com>:

**Comment by cathleruste** [comment]
Non, mais je peux modifier l'énoncé pour que la tortue doive parcourir 6km ^^

**Comment by mcodutti** [comment]
Ce qui rendrait le jeu non équitable pour la tortue ^^

2017-01-30 14:45 GMT+01:00 cathleruste <notifications@github.com>:

**Comment by cathleruste** [comment]
... c'est la vie ^^

**Comment by YoungFrog** [comment]
Ce n'est déjà pas équitable comme ça : pour que la tortue gagne il faut obtenir cinq fois "non 6" d'affilée, càd une probabilité de (5/6)^5 = 40.19%. Dans les autres cas (59.81%) c'est le lièvre qui gagne. Sur 6km, la proba de la tortue tombe à 33.49%. C'est encore moins cool, mais what did you expect ? C'est une tortue ! Bref, je passe à 6km et tant pis pour la tortue ;) Mais comme j'ai fait ça comme un pro, on peut changer à N km en changeant une seule variable.
