### ISSUE TITLE
Typos et autres remarques

### ISSUE THREAD

**Issue by drosebastien** [HEB-ESI/DEV2-ALG-Syllabus-Algo#77]
pg36 - classement triple - remarque
Je rajouterai que toute permutation est possible du fait qu'il n'y a pas de critère de précédence sur le champ option.

pg37 - notion de rupture - dernier paragraphe
Je rajouterai que malgré la coïncidence, il faut remarquer que les éléments <Durant Sam> et <Durant Kévin> se succèdent, mais pas dans le bon ordre (trié en mineur sur le prénom) => pas vraiment une coïncidence.

pg 38 - Rupture de niveau 1 - dernière phrase avant la solution : 
De plus l'algorithme serait aussi 
> fonctionnel -> Modulaire (ce n'est qu'une suggestion)

pg39 - Rupture de niveau 2 - toute dernière phrase
La phrase se termine par une virgule.

**Comment by cuv** [comment]
pg 40 ex 2: s/Compter les nombre/Compter le nombre/

**Comment by cuv** [comment]
pg41 ex4: 
La structure Participant est notée Voiture. 
On demande d'afficher le prénom qui n'existe pas dans la structure
pg41 ex7:
s/pas option/par option/

**Comment by YoungFrog** [comment]
> pg36 - classement triple - remarque
> Je rajouterai que toute permutation est possible du fait qu'il n'y a pas de critère de précédence sur le champ option.
> 
> pg37 - notion de rupture - dernier paragraphe
> Je rajouterai que malgré la coïncidence, il faut remarquer que les éléments et <Durant Kévin> se succèdent, mais pas dans le bon ordre (trié en mineur sur le prénom) => pas vraiment une coïncidence.

Je suggère de supprimer tout ce paragraphe. En ce qui me concerne je ne l'ai pas vraiment compris avant de lire l'algorithme, et je pense que c'est trop abstrait.

> pg 38 - Rupture de niveau 1 - dernière phrase avant la solution :
> De plus l'algorithme serait aussi
> 
>     fonctionnel -> Modulaire (ce n'est qu'une suggestion)

J'ai proposé une autre version.

> 
> pg39 - Rupture de niveau 2 - toute dernière phrase
> La phrase se termine par une virgule.

K

> 
> pg 40 ex 2: s/Compter les nombre/Compter le nombre/

K


> 
> pg41 ex4:
> La structure Participant est notée Voiture.

K

> On demande d'afficher le prénom qui n'existe pas dans la structure

le prénom est dans le champ "nom" (cf commentaire en regard de la déf du champ)

 
> pg41 ex7:
> s/pas option/par option/

K

J'ai ajouté des solutions à tous les problèmes énoncés ici (parfois radicales...) dans ma PR #78

**Comment by YoungFrog** [comment]
Pas de commentaires, je la ferme.
