### ISSUE TITLE
méthode getVainqueur de la classe LievreTortue 

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/DEV2-ALG-Syllabus-Algo#79]
je n'ai pas trouvé de référence au problème (?) que je signale ci-dessous. désolé du dérangement si j'ai mal cherché.

la méthode getVainqueur de la classe LievreTortue retourne soit Lièvre, soit Tortue. cela ne pose-t-il pas problème ? si la partie n'est pas finie, il n'y a pas de vainqueur, or dans ce cas, c'est Tortue qui est retourné. s'il s'agit non pas de retourner le vainqueur, mais le leader de la course, alors il faudrait changer le nom de la méthode et tenir compte de l'égalité des positions du lièvre et de la tortue en début de course.

**Comment by mcodutti** [comment]
Bonne remarque Nicolas.
Je vais indiquer que la méthode retourne `"aucun"` si la partie n'est pas finie et ajouter une remarque indiquant qu'en Java, on pourrait lancer une `IllegalStateException`.
Je suis (positivement) étonné qu'un prof lise le syllabus d'un cours qu'il ne donne pas ! C'est beau ;)
